/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
 */
package com.uber.api;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.uber.com/v1";

    //used for parsing and converting date formats\r\n");
    public static DateFormat dateFormat = new SimpleDateFormat();
    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "TODO: Replace";

}
