/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ProductCollection 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5428768011356335466L;
    private List<Product> products;
    /** GETTER
     * List of products
     */
    @JsonGetter("products")
    public List<Product> getProducts ( ) { 
        return this.products;
    }
    
    /** SETTER
     * List of products
     */
    @JsonSetter("products")
    public void setProducts (List<Product> value) { 
        this.products = value;
    }
 
}
 